language: python
sudo: required
python:
  - "2.7"
  - "3.5"
# command to install dependencies
install: 
  - pip install -r requirements.txt
  - python setup.py install
services:
- mongodb
addons:
  apt:
    sources:
    - mongodb-3.2-precise
    packages:
    - mongodb-org
before_script:
  - sleep 15
 - mongo phil_test --eval '(db.stats())'
# - mongo mydb_test --eval '(db.createUser({user: "travis", pwd: "test"}))'
# command to build and run tests
script:
  - mongo --version
