language: python
sudo: required
python:
  - "2.7"
  - "3.5"
# command to install dependencies
install:
  - pip install -r requirements.txt
  - python setup.py install
services:
  - mongodb
addons:
  apt:
    sources:
    - mongodb-3.2-precise
    packages:
    - mongodb-org
before_script:
  - sleep 5
# command to build and run tests
script:
  - mongo --version
  - mongo phil_test --eval '(db.stats())'
  - python setup.py test
  - python mdb_squish --help
  - python mdb_squish -v -d mongo_test --collections mongo_collection --log-dir . --stats-dir .
