language: python
python:
  - "2.7"
  - "3.5"
# command to install dependencies
install: 
  - pip install -r requirements.txt
  - python setup.py install
services: mongodb
before_script:
  - sleep 15
  - mongo mydb_test --eval 'db.addUser("travis", "test");
# command to build and run tests
script:
